name: "ğŸ” PR Check"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    name: "ğŸ“ Check PR Title"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥ Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "ğŸ” Verify PR title"
        uses: cocogitto/cocogitto-action@v4
        with:
          command: 'verify "${{ github.event.pull_request.title }}"'